apiVersion: v1
kind: Pod
metadata:
  name: aks-wi-env-check-pod
  namespace: default
  labels:
    azure.workload.identity/use: "true"
spec:
  containers:
  - name: aks-wi-env-check-container
    image: m8yng/aks-wi-env-check:latest # Swap registry if needed
    imagePullPolicy: Always
    env:
    - name: LANG_EXT
      value: "py" # py|go|rs
  serviceAccountName: workload-identity-sa # WI-enabled service account
  restartPolicy: Never # Run once, keep logs
